language: java

before_script:
  - ./script/build.sh

script:
  - export LD_LIBRARY_PATH="/home/travis/build/abstractj/kalium/libsodium-stable/vendor/lib"
  - mvn clean install

env: JAVA_OPTS="-Djava.library.path=/home/travis/build/abstractj/kalium/libsodium-stable/vendor/lib"

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk7
  - openjdk8

after_success:
  - rm -rf libsodium-stable*
